"""Maximum Entropy Spectral Analysis (MESA) strategy -- Burg's method.

Uses Burg's maximum-entropy method (MEM) to fit autoregressive models and
extract high-resolution power spectra from short price windows.  Dominant
market cycles are identified from spectral peaks, and trading signals are
generated by tracking the instantaneous phase of the dominant cycle via the
Hilbert transform of a bandpass-filtered price series.

Mathematical foundation
-----------------------
Maximum Entropy Principle:
    Among all power spectral densities S(f) consistent with the first p
    autocorrelation lags, choose the one that maximises the spectral entropy

        H = integral  log S(f) df

    This is equivalent to fitting an autoregressive model of order p whose
    prediction-error power equals the entropy-maximising spectrum.

Burg's algorithm:
    1.  Initialise forward/backward prediction errors as the centred data.
    2.  For m = 1, ..., p:
        a.  Compute the reflection coefficient k_m that minimises the total
            (forward + backward) prediction-error power (Levinson-Durbin
            lattice update).
        b.  Update the AR coefficients via the Levinson recursion.
        c.  Update forward/backward errors.
    3.  The maximum-entropy PSD is then

            S(f) = P_p / |1 + sum_{k=1}^{p} a_k e^{-j2pi f k}|^2

Advantages over FFT-based spectral estimation:
    *   Much better frequency resolution for short data windows (50--100 pts).
    *   No windowing artifacts (spectral leakage / sidelobes).
    *   Naturally extrapolates beyond the data length.
    *   Spectral peaks are sharper, enabling more precise cycle detection.

Strategy logic
--------------
1.  MESA Cycle Detection -- apply Burg's method on a rolling window of
    log-returns; compute S(f); identify dominant cycle period T_dom from the
    highest spectral peak.
2.  Dominant Cycle Trading -- bandpass-filter around T_dom, apply Hilbert
    transform to get instantaneous phase; buy at cycle trough (phase ~ -pi),
    sell at cycle peak (phase ~ 0).
3.  Cycle Stability -- track variance of T_dom over recent windows; stable
    cycles yield higher-confidence (larger) positions.
4.  Multi-Cycle Overlay -- when multiple significant peaks exist, combine
    signals weighted by their spectral power.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from scipy.signal import butter, sosfiltfilt, hilbert

from src.strategies.base import Strategy

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Burg's Maximum Entropy Method -- from scratch
# ---------------------------------------------------------------------------

def _burg_ar(
    x: np.ndarray,
    order: int,
) -> Tuple[np.ndarray, float]:
    """Estimate AR coefficients using Burg's method (Levinson-Durbin lattice).

    Implements the algorithm described in:
        S.L. Marple, *Digital Spectral Analysis with Applications*,
        Prentice Hall, 1987, Chapter 8.

    The AR model convention used here is::

        x[n] + a[0]*x[n-1] + a[1]*x[n-2] + ... + a[p-1]*x[n-p] = e[n]

    so that the power spectral density is::

        S(f) = pm / |1 + sum_{k=1}^{p} a[k-1] * exp(-j*2*pi*f*k)|^2

    Parameters
    ----------
    x : 1-D array
        Zero-mean input signal of length N.
    order : int
        AR model order p.

    Returns
    -------
    a : 1-D array of length *order*
        AR coefficients [a_1, a_2, ..., a_p] in the convention above.
    pm : float
        Prediction error power (variance of the innovations).

    Raises
    ------
    ValueError
        If *order* >= len(x) or data is degenerate.

    Notes
    -----
    The reflection coefficients are computed to jointly minimise the sum
    of forward and backward prediction-error powers -- this is the
    distinguishing feature of Burg's algorithm versus other AR estimators
    (e.g. Yule-Walker, covariance method).  The denominator is updated
    incrementally for numerical efficiency.
    """
    x = np.asarray(x, dtype=np.float64)
    n = len(x)
    if order >= n:
        raise ValueError(
            f"AR order ({order}) must be less than data length ({n})."
        )
    if order == 0:
        return np.array([], dtype=np.float64), float(np.dot(x, x) / n)

    # Initialise forward and backward prediction errors
    ef = x[1:n].copy()   # forward errors:  ef[i] = x[i+1]
    eb = x[0:n-1].copy() # backward errors: eb[i] = x[i]

    # AR coefficients built up iteratively
    a = np.zeros(order, dtype=np.float64)

    # Denominator for the reflection coefficient (updated incrementally)
    den = float(np.dot(ef, ef) + np.dot(eb, eb))

    # Total squared error (= n * prediction_error_power)
    err = float(np.dot(x, x))

    for m in range(order):
        # --- Reflection coefficient k_{m+1} ---
        num = -2.0 * float(np.dot(eb, ef))

        if abs(den) < 1e-30:
            break

        k = num / den

        # Stability check: |k| must be < 1 for a stable AR model
        if abs(k) >= 1.0:
            break

        # Update total error
        err *= (1.0 - k * k)

        # --- Levinson-Durbin recursion for AR coefficients ---
        if m == 0:
            a[0] = k
        else:
            a_prev = a[:m].copy()
            a[:m] = a_prev + k * a_prev[::-1]
            a[m] = k

        # --- Update forward/backward errors (lattice step) ---
        if len(ef) <= 1:
            break
        ef_old = ef.copy()
        ef = ef_old[1:] + k * eb[1:]
        eb = eb[:-1] + k * ef_old[:-1]

        # Incremental denominator update (avoids O(N) recomputation)
        den = (1.0 - k * k) * den - ef_old[0] ** 2 - eb[-1] ** 2

        # Safety: if incremental update goes non-positive due to
        # numerical issues, recompute from scratch
        if den <= 0:
            den = float(np.dot(ef, ef) + np.dot(eb, eb))

    pm = err / n
    return a, pm


def _mesa_spectrum(
    a: np.ndarray,
    pm: float,
    n_freqs: int = 512,
    dt: float = 1.0,
) -> Tuple[np.ndarray, np.ndarray]:
    """Compute the maximum entropy power spectral density from AR coefficients.

    Parameters
    ----------
    a : 1-D array
        AR coefficients [a_1, ..., a_p].
    pm : float
        Prediction error power.
    n_freqs : int
        Number of frequency bins in [0, f_Nyquist].
    dt : float
        Sampling interval (1.0 for daily data).

    Returns
    -------
    freqs : 1-D array of length *n_freqs*
        Frequency values in [0, 0.5/dt].
    psd : 1-D array of length *n_freqs*
        Power spectral density at each frequency.

    Notes
    -----
    Uses the Burg convention where the AR model is
    ``x[n] + a_1 x[n-1] + ... = e[n]``, giving::

        S(f) = (pm * dt) / |1 + sum_{k=1}^{p} a_k e^{-j 2 pi f k dt}|^2
    """
    freqs = np.linspace(0, 0.5 / dt, n_freqs, endpoint=False)
    p = len(a)
    if p == 0:
        return freqs, np.full(n_freqs, pm * dt)

    # Build the AR polynomial denominator evaluated at each frequency
    # A(f) = 1 + sum_{k=1}^{p} a_k * exp(-j * 2*pi * f * k * dt)
    k_idx = np.arange(1, p + 1)  # shape (p,)
    # Outer product: phase matrix (n_freqs, p)
    phase = -2.0 * np.pi * dt * np.outer(freqs, k_idx)
    # A(f) for each frequency
    ar_poly = 1.0 + np.sum(a[np.newaxis, :] * np.exp(1j * phase), axis=1)

    psd = (pm * dt) / np.abs(ar_poly) ** 2
    return freqs, psd


# ---------------------------------------------------------------------------
# Model order selection via AIC
# ---------------------------------------------------------------------------

def _select_ar_order(
    x: np.ndarray,
    max_order: int,
    criterion: str = "aic",
) -> int:
    """Select optimal AR order by minimising information criterion.

    Parameters
    ----------
    x : 1-D array
        Zero-mean input signal.
    max_order : int
        Maximum AR order to consider.
    criterion : {'aic', 'bic'}
        Information criterion.

    Returns
    -------
    int
        Selected AR model order (>= 1).
    """
    n = len(x)
    best_order = 1
    best_ic = np.inf

    for p in range(1, max_order + 1):
        try:
            _, pm = _burg_ar(x, p)
        except ValueError:
            break
        if pm <= 0:
            pm = 1e-30

        log_pm = np.log(pm)
        if criterion == "aic":
            ic = n * log_pm + 2.0 * p
        else:  # BIC
            ic = n * log_pm + p * np.log(n)

        if ic < best_ic:
            best_ic = ic
            best_order = p

    return best_order


# ---------------------------------------------------------------------------
# Spectral peak detection
# ---------------------------------------------------------------------------

def _find_spectral_peaks(
    freqs: np.ndarray,
    psd: np.ndarray,
    min_period: float = 5.0,
    max_period: float = 200.0,
    peak_to_bg_threshold: float = 3.0,
    max_peaks: int = 5,
) -> List[Dict[str, float]]:
    """Identify significant peaks in the MESA power spectrum.

    Parameters
    ----------
    freqs : 1-D array
        Frequency values (cycles per sample).
    psd : 1-D array
        Power spectral density.
    min_period : float
        Minimum cycle period (in samples) to consider.
    max_period : float
        Maximum cycle period (in samples) to consider.
    peak_to_bg_threshold : float
        Minimum ratio of peak power to median (background) power for a peak
        to be considered significant.
    max_peaks : int
        Maximum number of peaks to return.

    Returns
    -------
    list of dict
        Each dict has keys 'frequency', 'period', 'power', 'peak_ratio'.
        Sorted by descending power.
    """
    # Convert period bounds to frequency bounds
    f_min = 1.0 / max_period if max_period > 0 else 0.0
    f_max = 1.0 / min_period if min_period > 0 else 0.5

    # Mask to valid frequency range (exclude DC)
    valid = (freqs > f_min) & (freqs <= f_max) & (freqs > 0)
    if not np.any(valid):
        return []

    valid_freqs = freqs[valid]
    valid_psd = psd[valid]

    # Background level: median power in the valid range
    bg_power = np.median(valid_psd)
    if bg_power <= 0:
        bg_power = 1e-30

    # Simple peak detection: local maxima that exceed threshold
    peaks = []
    for i in range(1, len(valid_psd) - 1):
        if valid_psd[i] > valid_psd[i - 1] and valid_psd[i] > valid_psd[i + 1]:
            ratio = valid_psd[i] / bg_power
            if ratio >= peak_to_bg_threshold:
                peaks.append({
                    "frequency": float(valid_freqs[i]),
                    "period": float(1.0 / valid_freqs[i]),
                    "power": float(valid_psd[i]),
                    "peak_ratio": float(ratio),
                })

    # Sort by power (descending) and keep top max_peaks
    peaks.sort(key=lambda p: p["power"], reverse=True)
    return peaks[:max_peaks]


# ---------------------------------------------------------------------------
# Bandpass filter + Hilbert phase extraction
# ---------------------------------------------------------------------------

def _bandpass_filter(
    x: np.ndarray,
    center_period: float,
    bandwidth_fraction: float = 0.3,
    dt: float = 1.0,
    filter_order: int = 3,
) -> np.ndarray:
    """Apply a Butterworth bandpass filter centred on *center_period*.

    Parameters
    ----------
    x : 1-D array
        Input signal.
    center_period : float
        Centre period of the bandpass (in samples).
    bandwidth_fraction : float
        Fractional bandwidth around the centre frequency.  E.g. 0.3 means
        the passband spans [0.7*f_c, 1.3*f_c].
    dt : float
        Sampling interval.
    filter_order : int
        Butterworth filter order.

    Returns
    -------
    1-D array
        Bandpass-filtered signal (same length as *x*).
    """
    f_center = 1.0 / center_period
    f_low = f_center * (1.0 - bandwidth_fraction)
    f_high = f_center * (1.0 + bandwidth_fraction)

    # Nyquist frequency
    f_nyq = 0.5 / dt

    # Normalise to [0, 1] range for scipy
    low = max(f_low / f_nyq, 1e-6)
    high = min(f_high / f_nyq, 1.0 - 1e-6)

    if low >= high:
        return np.zeros_like(x)

    try:
        sos = butter(filter_order, [low, high], btype="band", output="sos")
        filtered = sosfiltfilt(sos, x)
    except (ValueError, np.linalg.LinAlgError):
        return np.zeros_like(x)

    return filtered


def _hilbert_phase(signal: np.ndarray) -> np.ndarray:
    """Extract instantaneous phase via the Hilbert transform.

    Returns
    -------
    phase : 1-D array
        Unwrapped instantaneous phase in radians.
    """
    analytic = hilbert(signal)
    phase = np.unwrap(np.angle(analytic))
    return phase


# ---------------------------------------------------------------------------
# Polynomial detrending
# ---------------------------------------------------------------------------

def _poly_detrend(x: np.ndarray, order: int = 3) -> np.ndarray:
    """Remove polynomial trend of given order from *x* and centre to zero mean.

    Using a cubic (order=3) polynomial removes slow trends and low-frequency
    curvature that would otherwise dominate the AR model and cause the
    reflection coefficients to saturate near +/-1, breaking Burg's method.

    Parameters
    ----------
    x : 1-D array
        Input signal.
    order : int
        Polynomial order for detrending (default 3 = cubic).

    Returns
    -------
    1-D array
        Detrended, zero-mean signal.
    """
    n = len(x)
    t = np.arange(n, dtype=np.float64)
    coeffs = np.polyfit(t, x, order)
    trend = np.polyval(coeffs, t)
    detrended = x - trend
    detrended -= detrended.mean()
    return detrended


# ---------------------------------------------------------------------------
# Cycle stability measurement
# ---------------------------------------------------------------------------

def _cycle_stability(
    dominant_periods: np.ndarray,
    lookback: int = 10,
) -> np.ndarray:
    """Compute rolling coefficient of variation of the dominant cycle period.

    A low CV indicates a stable, reliable cycle.

    Parameters
    ----------
    dominant_periods : 1-D array
        Time series of dominant cycle periods (may contain NaN).
    lookback : int
        Rolling window for CV calculation.

    Returns
    -------
    stability : 1-D array
        Values in [0, 1] where 1 = perfectly stable cycle, 0 = unstable.
        NaN where insufficient data.
    """
    n = len(dominant_periods)
    stability = np.full(n, np.nan)
    for i in range(lookback - 1, n):
        window = dominant_periods[i - lookback + 1 : i + 1]
        valid = window[~np.isnan(window)]
        if len(valid) < lookback // 2:
            continue
        mean_p = np.mean(valid)
        if mean_p < 1e-10:
            continue
        cv = np.std(valid) / mean_p
        # Map CV to stability: CV=0 -> 1.0, CV=1 -> ~0.27
        stability[i] = np.exp(-cv * cv)
    return stability


# ===========================================================================
# Strategy class
# ===========================================================================

class MaxEntropySpectrumStrategy(Strategy):
    """Maximum Entropy Spectral Analysis (MESA) trading strategy.

    Uses Burg's method to fit high-resolution AR spectral models on short
    rolling windows of log-returns, identifies dominant market cycles from
    spectral peaks, and trades the phase of those cycles.

    Parameters
    ----------
    window : int
        Rolling window (trading days) for the MESA analysis.  Burg's method
        works well with windows as small as 50--100 samples.
    max_ar_order : int
        Maximum AR model order to evaluate.  The actual order is selected
        by minimising AIC.
    n_freqs : int
        Number of frequency bins for the computed spectrum.
    min_period : float
        Minimum cycle period (days) to consider as a tradeable cycle.
    max_period : float
        Maximum cycle period (days) to consider.
    peak_threshold : float
        Minimum peak-to-background power ratio for a spectral peak to be
        considered significant.
    bandwidth_frac : float
        Fractional bandwidth of the bandpass filter around the dominant
        cycle frequency.
    stability_lookback : int
        Number of recent windows used to assess cycle stability (CV).
    stability_min : float
        Minimum stability score [0, 1] required to trade.  Set to 0 to
        disable the stability filter.
    phase_buy : float
        Phase (radians) at which to go long.  Default -pi (cycle trough).
    phase_sell : float
        Phase (radians) at which to go short.  Default 0 (cycle peak).
    phase_tolerance : float
        Half-width of the phase window around buy/sell phases (radians).
    max_cycles : int
        Maximum number of spectral peaks to overlay in the multi-cycle
        composite signal.
    """

    def __init__(
        self,
        window: int = 80,
        max_ar_order: int = 30,
        n_freqs: int = 512,
        min_period: float = 5.0,
        max_period: float = 120.0,
        peak_threshold: float = 3.0,
        bandwidth_frac: float = 0.3,
        stability_lookback: int = 10,
        stability_min: float = 0.2,
        phase_buy: float = -np.pi,
        phase_sell: float = 0.0,
        phase_tolerance: float = np.pi / 4,
        max_cycles: int = 3,
    ) -> None:
        super().__init__(
            name="MaxEntropySpectrum",
            description=(
                "Maximum Entropy Spectral Analysis (MESA) strategy using "
                "Burg's method for high-resolution cycle detection and "
                "phase-based trading."
            ),
        )
        self.window = window
        self.max_ar_order = max_ar_order
        self.n_freqs = n_freqs
        self.min_period = min_period
        self.max_period = max_period
        self.peak_threshold = peak_threshold
        self.bandwidth_frac = bandwidth_frac
        self.stability_lookback = stability_lookback
        self.stability_min = stability_min
        self.phase_buy = phase_buy
        self.phase_sell = phase_sell
        self.phase_tolerance = phase_tolerance
        self.max_cycles = max_cycles

        # Populated by fit()
        self._fitted_params: Dict[str, Any] = {}

    # -----------------------------------------------------------------
    # Core MESA analysis for a single window
    # -----------------------------------------------------------------

    def _analyse_window(
        self, x: np.ndarray
    ) -> Tuple[Optional[int], np.ndarray, np.ndarray, List[Dict[str, float]]]:
        """Run Burg's method and spectral peak detection on a single window.

        Parameters
        ----------
        x : 1-D array
            Zero-mean log-return (or detrended log-price) window.

        Returns
        -------
        ar_order : int or None
            Selected AR model order (None if analysis failed).
        freqs : 1-D array
            Frequency grid.
        psd : 1-D array
            Power spectral density.
        peaks : list of peak dicts
            Significant spectral peaks found.
        """
        n = len(x)
        max_p = min(self.max_ar_order, n // 2 - 1)
        if max_p < 1:
            return None, np.array([]), np.array([]), []

        try:
            ar_order = _select_ar_order(x, max_p)
            a, pm = _burg_ar(x, ar_order)
        except (ValueError, FloatingPointError):
            return None, np.array([]), np.array([]), []

        freqs, psd = _mesa_spectrum(a, pm, n_freqs=self.n_freqs)
        peaks = _find_spectral_peaks(
            freqs,
            psd,
            min_period=self.min_period,
            max_period=self.max_period,
            peak_to_bg_threshold=self.peak_threshold,
            max_peaks=self.max_cycles,
        )
        return ar_order, freqs, psd, peaks

    # -----------------------------------------------------------------
    # Single-asset signal generation (rolling)
    # -----------------------------------------------------------------

    def _generate_single_asset_signals(
        self,
        prices: pd.Series,
    ) -> Tuple[pd.Series, pd.Series]:
        """Produce signal and weight series for one asset.

        Returns
        -------
        signal : pd.Series
            Values in {-1, 0, +1}.
        weight : pd.Series
            Position-sizing weight in [0, 1].
        """
        n = len(prices)
        price_vals = prices.values.astype(np.float64)

        # Guard against non-positive prices
        price_vals = np.where(price_vals <= 0, np.nan, price_vals)
        log_p = np.log(price_vals)

        signal_out = np.zeros(n)
        weight_out = np.zeros(n)

        # Track dominant period over time for stability calculation
        dom_period_history = np.full(n, np.nan)

        w = self.window

        for t in range(w, n):
            window_data = log_p[t - w : t]
            if np.any(np.isnan(window_data)):
                continue

            # Detrend: remove polynomial trend for spectral analysis.
            # Cubic detrending removes slow curvature that would otherwise
            # cause Burg's reflection coefficients to saturate near +/-1.
            detrended = _poly_detrend(window_data, order=3)

            # Run MESA analysis
            _, _, _, peaks = self._analyse_window(detrended)
            if not peaks:
                continue

            # Record dominant period
            dom_period_history[t] = peaks[0]["period"]

            # --- Multi-cycle composite signal ---
            # Weight each cycle's contribution by its spectral power
            total_power = sum(pk["power"] for pk in peaks)
            if total_power <= 0:
                continue

            composite_signal = 0.0
            total_weight = 0.0

            for pk in peaks:
                period = pk["period"]
                power_weight = pk["power"] / total_power

                # Need enough data for bandpass filtering (at least 3 cycles)
                min_required = max(int(3 * period), w)
                lookback_start = max(0, t - min_required)
                bp_data = log_p[lookback_start : t]

                if len(bp_data) < int(2 * period):
                    # Not enough data for this cycle -- skip
                    continue

                # Detrend the longer segment for filtering
                bp_detrended = _poly_detrend(bp_data, order=3)

                # Bandpass filter around the cycle frequency
                filtered = _bandpass_filter(
                    bp_detrended,
                    center_period=period,
                    bandwidth_fraction=self.bandwidth_frac,
                )

                if np.all(np.abs(filtered) < 1e-15):
                    continue

                # Extract phase at the current point (last sample)
                phase = _hilbert_phase(filtered)
                current_phase = phase[-1]

                # Wrap phase to [-pi, pi]
                current_phase = (current_phase + np.pi) % (2 * np.pi) - np.pi

                # Phase-based signal:
                # Buy zone:  phase near phase_buy (trough, default -pi)
                # Sell zone: phase near phase_sell (peak, default 0)
                buy_dist = min(
                    abs(current_phase - self.phase_buy),
                    abs(current_phase - self.phase_buy - 2 * np.pi),
                    abs(current_phase - self.phase_buy + 2 * np.pi),
                )
                sell_dist = min(
                    abs(current_phase - self.phase_sell),
                    abs(current_phase - self.phase_sell - 2 * np.pi),
                    abs(current_phase - self.phase_sell + 2 * np.pi),
                )

                if buy_dist <= self.phase_tolerance:
                    cycle_signal = 1.0
                elif sell_dist <= self.phase_tolerance:
                    cycle_signal = -1.0
                else:
                    cycle_signal = 0.0

                composite_signal += power_weight * cycle_signal
                total_weight += power_weight

            if total_weight <= 0:
                continue

            composite_signal /= total_weight

            # Discretise composite signal
            if composite_signal > 0.3:
                signal_out[t] = 1.0
            elif composite_signal < -0.3:
                signal_out[t] = -1.0
            else:
                signal_out[t] = 0.0

        # --- Cycle stability weighting ---
        stability = _cycle_stability(
            dom_period_history, lookback=self.stability_lookback
        )

        for t in range(n):
            if signal_out[t] == 0.0:
                weight_out[t] = 0.0
                continue

            stab = stability[t] if not np.isnan(stability[t]) else 0.0
            if stab < self.stability_min:
                # Cycle too unstable -- suppress signal
                signal_out[t] = 0.0
                weight_out[t] = 0.0
            else:
                # Weight proportional to stability
                weight_out[t] = np.clip(stab, 0.0, 1.0)

        signal_series = pd.Series(signal_out, index=prices.index, name="signal")
        weight_series = pd.Series(weight_out, index=prices.index, name="weight")
        return signal_series, weight_series

    # -----------------------------------------------------------------
    # Public interface
    # -----------------------------------------------------------------

    def fit(self, prices: pd.DataFrame, **kwargs: Any) -> "MaxEntropySpectrumStrategy":
        """Calibrate strategy parameters on historical price data.

        Calibration steps:
        1.  Run MESA analysis on the training data to determine the
            distribution of dominant cycle periods per asset.
        2.  Store the median dominant period and optimal AR order to use
            as priors / starting points for live signal generation.
        3.  Validate that meaningful cycles exist in the training data.

        Parameters
        ----------
        prices : pd.DataFrame
            Historical price data (columns = tickers, DatetimeIndex).

        Returns
        -------
        self
        """
        self.validate_prices(prices)

        fitted_info: Dict[str, Dict[str, Any]] = {}

        for col in prices.columns:
            series = prices[col].dropna()
            if len(series) < self.window + self.stability_lookback:
                logger.info(
                    "Skipping %s during fit: insufficient data (%d < %d).",
                    col,
                    len(series),
                    self.window + self.stability_lookback,
                )
                continue

            price_vals = series.values.astype(np.float64)
            price_vals = np.where(price_vals <= 0, np.nan, price_vals)
            log_p = np.log(price_vals)

            # Collect dominant periods and AR orders across the training set
            dom_periods: List[float] = []
            ar_orders: List[int] = []

            step = max(self.window // 4, 1)
            for t in range(self.window, len(log_p), step):
                window_data = log_p[t - self.window : t]
                if np.any(np.isnan(window_data)):
                    continue

                detrended = _poly_detrend(window_data, order=3)

                ar_order, _, _, peaks = self._analyse_window(detrended)
                if ar_order is not None:
                    ar_orders.append(ar_order)
                if peaks:
                    dom_periods.append(peaks[0]["period"])

            info: Dict[str, Any] = {
                "n_windows_analysed": len(ar_orders),
                "cycles_found": len(dom_periods),
            }

            if dom_periods:
                info["median_dominant_period"] = float(np.median(dom_periods))
                info["mean_dominant_period"] = float(np.mean(dom_periods))
                info["std_dominant_period"] = float(np.std(dom_periods))
            if ar_orders:
                info["median_ar_order"] = int(np.median(ar_orders))

            fitted_info[col] = info

        self._fitted_params = fitted_info
        self.parameters = {
            "window": self.window,
            "max_ar_order": self.max_ar_order,
            "peak_threshold": self.peak_threshold,
            "fitted_assets": list(fitted_info.keys()),
        }
        self._fitted = True
        logger.info(
            "MaxEntropySpectrum fitted on %d asset(s).",
            len(fitted_info),
        )
        return self

    def generate_signals(
        self, prices: pd.DataFrame, **kwargs: Any
    ) -> pd.DataFrame:
        """Generate trading signals from price data.

        For each asset, runs rolling MESA analysis, identifies dominant
        cycles, and produces phase-based signals weighted by cycle
        stability.

        Parameters
        ----------
        prices : pd.DataFrame
            OHLCV or adjusted-close price data (columns = tickers,
            DatetimeIndex).

        Returns
        -------
        pd.DataFrame
            Contains ``{ticker}_signal`` and ``{ticker}_weight`` columns
            for each ticker, or ``signal`` / ``weight`` for single-ticker
            data.
        """
        self.validate_prices(prices)

        result = pd.DataFrame(index=prices.index)

        if prices.ndim == 1 or len(prices.columns) == 1:
            # Single asset
            series = prices.iloc[:, 0] if prices.ndim == 2 else prices
            sig, wt = self._generate_single_asset_signals(series)
            result["signal"] = sig
            result["weight"] = wt
        else:
            # Multiple assets
            for col in prices.columns:
                series = prices[col].dropna()
                if len(series) < self.window:
                    result[f"{col}_signal"] = 0.0
                    result[f"{col}_weight"] = 0.0
                    continue

                sig, wt = self._generate_single_asset_signals(series)
                # Reindex to full date range
                result[f"{col}_signal"] = sig.reindex(prices.index, fill_value=0.0)
                result[f"{col}_weight"] = wt.reindex(prices.index, fill_value=0.0)

        return result
